### ISSUE TITLE
refactoring: use a config.ini file instead of arguments

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#104]

**Comment by monperrus** [comment]
I'm not fan of .ini.

I would prefer to be able to pass the command line in a file, (possibly containing line breaks)

**Comment by surli** [comment]
> I'm not fan of .ini.
What's the problem with .ini file?

> I would prefer to be able to pass the command line in a file, (possibly containing line breaks)
It's already possible using bash redirection I think
