### ISSUE TITLE
Change getPrettyPrintState in AbstractDataSerializer to handle with the new status related to SquashRepository step.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#170]
The status is appearing as "unknown" in the spreadsheets.

**Comment by fermadeiral** [comment]
Maybe is this the reason I'm not getting builds with status `FIXERBUILD_CASE1` and `FIXERBUILD_CASE2` (the interesting ones) the last week? If so, thank God, because then it means we have had bugs without noticing, and then it doesn't mean that there is a lack of bugs.

**Comment by surli** [comment]
Don't you have the real status in your spreadsheet?

**Comment by fermadeiral** [comment]
Yes, I have, but I always look at the pretty status that should make the data easier to analyze---it becomes pink if it is the interesting status (`FIXERBUILD_CASE`). My mistake, because I didn't notice I haven't had builds with the `FIXERBUILD_CASE` status because of the new step.
