### ISSUE TITLE
Change Push step for Bears.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#212]
- For failing/passing case:
-- To reproduce the bug: push commit of the previous build (the failing one)

- For passing/passing case:
-- To reproduce the bug: push every file from the second build except by the source code folder that must be from the first build

- For the two cases:
-- To reproduce the fix: push commit of the passing build (the passing one)
-- push the other files (our files, with properties, etc.)

**Comment by surli** [comment]
Done in #237
