### ISSUE TITLE
Bears: push state of the final bench repo

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#235]
1. Push the state of the failing build (should fail on mvn test)
2. Push repairnator.json 
3. Push a patch.diff (should be usable with git patch and should pass with mvn test then)
4. (optional) push logs

**Comment by surli** [comment]
Done in #237 on the form of 2 or more commits:

- Commit of the bug
- Commit of automated patch and / or repair info (logs, properties..)
- Commit of the human patch when available
