### ISSUE TITLE
ComputeSourceDir step: sometimes the pom file seems not to be found

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#239]
See with the following build: https://travis-ci.org/junit-team/junit5/builds/218208508

> 16:12:54.846 [main] DEBUG f.i.s.r.p.step.ComputeSourceDir - Computing the source directory ...
> 16:12:54.846 [main] DEBUG f.i.s.r.p.step.ComputeSourceDir - The default source directory (./workspace/junit-team/junit5/218203599/src/main/java) does not exists. Try to read pom.xml to get informations.
> 16:12:54.902 [main] ERROR f.i.s.r.p.step.ComputeSourceDir - Error while building pom.xml model: org.apache.maven.model.building.ModelBuildingException: 1 problem was encountered while building the effective model
> [FATAL] Non-readable POM /home/spirals/librepair/github/librepair/repairnator/./workspace/junit-team/junit5/218203599/pom.xml: /home/spirals/librepair/github/librepair/repairnator/./workspace/junit-team/junit5/218203599/pom.xml (No such file or directory) @
> 
> 16:12:54.902 [main] ERROR f.i.s.r.p.step.ComputeSourceDir - Source directory is not at default location or specified in build section and no parent can be found.
> 16:12:54.902 [main] ERROR f.i.s.r.p.step.ComputeSourceDir - Fail to find the sources directory.
> 16:12:54.904 [main] DEBUG f.i.s.r.p.s.c.CheckoutBuggyBuildSourceCode - Checking out the source code of the previous build...
> 16:12:54.905 [main] ERROR f.i.s.r.p.s.c.CheckoutBuggyBuildSourceCode - Repair source dir is null: it is therefore impossible to continue.

**Comment by surli** [comment]
Actually it's normal, this one can't be checked out: there is no pom.xml file in the repository... @fermadeiral did you see another build with the same bug?

**Comment by fermadeiral** [comment]
@surli  Yes, I saw other builds where the same error happen.

**Comment by surli** [comment]
> @surli Yes, I saw other builds where the same error happen.

Could you point them out?

**Comment by fermadeiral** [comment]
@surli  Sure:
http://travis-ci.org/eclipse/kura/builds/218149734
http://travis-ci.org/eclipse/kura/builds/218163495
http://travis-ci.org/treasure-data/digdag/builds/218169161
http://travis-ci.org/aimacode/aima-java/builds/218180742

I can get more if you want. Actually, from all of the builds that real status is `PREVIOUSBUILDCODENOTCHECKEDOUT` that I've manually analyzed, the most of them presents this error.
