### ISSUE TITLE
collect the list of projects for which we have at least one failing_passing

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#248]

**Comment by surli** [comment]
[list_counted.txt](https://github.com/Spirals-Team/librepair/files/970914/list_counted.txt)
Here is the complete list.

**Comment by surli** [comment]
And here is the list of 50 considered projects: 
[50-projects.txt](https://github.com/Spirals-Team/librepair/files/970918/50-projects.txt)
