### ISSUE TITLE
compute overall metrics from set of repairnator.json files

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#250]
Overall metrics (computed from repairnator.json files)

- [x] Number of bugs (-> number of branches in the repo)
- [x] Number of projects with bugs
- [x] Number of exception types
- [x] Number of failing/passing and passing/passing bugs
- [x] Distribution of error types by project
- Distribution of build time (median/average)

**Comment by monperrus** [comment]
PR to be merged

**Comment by fermadeiral** [comment]
But this one is finished (the implementation)...

**Comment by surli** [comment]
Ok so I assume you pushed everything if I want to make some changes to get other information ;)

**Comment by fermadeiral** [comment]
You can just ask me in a nice way, and then I can get other information for you ;P
