### ISSUE TITLE
Changes in repairnator.json file.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#267]
To remove:
- "buildid"
- "workspace"
- "bugRepo" and "repo" are the same thing. One can be removed (and there is also "RepoSlug" inside metrics (to remove too)
- there are some duplicated info as nbLibraries, nbCPU and totalMemory

To add:
- reproduction day

Can I choose the order of the info in the file? It's a little bit difficult to follow the information sometimes because of the order...

**Comment by surli** [comment]
> Can I choose the order of the info in the file? It's a little bit difficult to follow the information sometimes because of the order...

Not totally sure about that, but tell me the order and I'll see what I can do.

**Comment by surli** [comment]
> "bugRepo" and "repo" are the same thing. One can be removed (and there is also "RepoSlug" inside metrics (to remove too)

Ok I kept "repo". So tell me for the order
