### ISSUE TITLE
Pushing builds into a repository.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#27]
For Bears, it'll be also necessary pushing builds (or parts of them) into a repository.

The issue is: do I push the builds for Bears into a (new) folder in the repository of builds for Repairnator (https://github.com/Spirals-Team/librepair-experiments) or do I create a new repository for this?

**Comment by surli** [comment]
As we already create new branches for each reproduced failing build in librepair, I suggest to create another repository, WDYT @monperrus ?

**Comment by monperrus** [comment]
> I suggest to create another repository

Good idea. In https://github.com/Spirals-Team/bears-benchmark
