### ISSUE TITLE
Display database data on a webpage

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#279]
Show same information as spreadsheet on a URL from database. Put it in: repairnator.lille.inria.fr/realtime.html

**Comment by surli** [comment]
Improve view of information : 

 - [ ] Clickable link of Travis URL
 - [ ] Delete "_id" data

**Comment by monperrus** [comment]
in column "Type of failures" separate exception by a space (`, `) so as to have line break in the table.

**Comment by monperrus** [comment]
otherwise, it looks really nice, good work!
