### ISSUE TITLE
add script to suppress branches of librepair-experiments that do not contain repairnator.json

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#281]
(so as to clean afterwards)

**Comment by surli** [comment]
Created and applied. 
It deleted the following 514 branches:

To github.com:Spirals-Team/librepair-experiments.git
 - [deleted]         4pr0n-ripme-196568333-20170130-124242
 - [deleted]         4pr0n-ripme-197498564-20170202-004235
 - [deleted]         4pr0n-ripme-197747240-20170202-184633
 - [deleted]         4pr0n-ripme-198414128-20170204-211919
 - [deleted]         4pr0n-ripme-199527447-20170208-080902
 - [deleted]         4pr0n-ripme-199923736-20170209-101805
 - [deleted]         4pr0n-ripme-203934220-20170221-203251
 - [deleted]         4pr0n-ripme-203934376-20170221-203322
 - [deleted]         4pr0n-ripme-203935775-20170221-203755
 - [deleted]         4pr0n-ripme-203958007-20170221-214602
 - [deleted]         4pr0n-ripme-203961440-20170221-215609
 - [deleted]         4pr0n-ripme-203989986-20170221-231527
 - [deleted]         4pr0n-ripme-204084848-20170222-072539
 - [deleted]         4pr0n-ripme-204222281-20170222-155641
 - [deleted]         4pr0n-ripme-204226527-20170222-160914
 - [deleted]         4pr0n-ripme-206927001-20170302-101646
 - [deleted]         4pr0n-ripme-206928572-20170302-102301
 - [deleted]         4pr0n-ripme-206930844-20170302-103208
 - [deleted]         4pr0n-ripme-206934054-20170302-104347
 - [deleted]         4pr0n-ripme-206935002-20170302-104656
 - [deleted]         4pr0n-ripme-206935037-20170302-104709
 - [deleted]         4pr0n-ripme-210679328-20170313-201610
 - [deleted]         4pr0n-ripme-210713281-20170313-215606
 - [deleted]         4pr0n-ripme-210929340-20170314-134114
 - [deleted]         4pr0n-ripme-211026742-20170314-170755
 - [deleted]         4pr0n-ripme-212282420-20170317-223806
 - [deleted]         4pr0n-ripme-212295250-20170317-231351
 - [deleted]         4pr0n-ripme-212738622-20170319-184821
 - [deleted]         4pr0n-ripme-212808975-20170319-233503
 - [deleted]         4pr0n-ripme-212810978-20170319-234240
 - [deleted]         4pr0n-ripme-212824281-20170320-005357
 - [deleted]         4pr0n-ripme-214146675-20170323-084709
 - [deleted]         4pr0n-ripme-214146784-20170323-084723
 - [deleted]         4pr0n-ripme-214154602-20170323-091919
 - [deleted]         4pr0n-ripme-214173833-20170323-103633
 - [deleted]         4pr0n-ripme-214174804-20170323-104050
 - [deleted]         4pr0n-ripme-214174921-20170323-104127
 - [deleted]         4pr0n-ripme-214485842-20170324-020853
 - [deleted]         4pr0n-ripme-214817861-20170324-225328
 - [deleted]         4pr0n-ripme-214826914-20170324-232234
 - [deleted]         4pr0n-ripme-214957062-20170325-131107
 - [deleted]         4pr0n-ripme-215939609-20170328-153651
 - [deleted]         4pr0n-ripme-216071907-20170328-212047
 - [deleted]         4pr0n-ripme-216180260-20170329-040358
 - [deleted]         4pr0n-ripme-216183914-20170329-042737
 - [deleted]         4pr0n-ripme-216191497-20170329-050929
 - [deleted]         4pr0n-ripme-219133198-20170406-053619
 - [deleted]         4pr0n-ripme-219133450-20170406-053733
 - [deleted]         4pr0n-ripme-219135270-20170406-055028
 - [deleted]         Adobe-Consulting-Services-acs-aem-commons-200913584-20170212-183533
 - [deleted]         Adobe-Consulting-Services-acs-aem-commons-200921828-20170212-183105
 - [deleted]         Adobe-Consulting-Services-acs-aem-commons-200926936-20170212-185859
 - [deleted]         Asqatasun-Asqatasun-208879284-20170308-085158
 - [deleted]         AsyncHttpClient-async-http-client-199372049-20170207-204744
 - [deleted]         AsyncHttpClient-async-http-client-199372870-20170207-205045
 - [deleted]         AsyncHttpClient-async-http-client-210961079-20170314-142728
 - [deleted]         AsyncHttpClient-async-http-client-215875330-20170328-120825
 - [deleted]         AsyncHttpClient-async-http-client-216670046-20170330-104141
 - [deleted]         AxonFramework-AxonFramework-218785400-20170405-101407
 - [deleted]         ButterFaces-ButterFaces-226399950-20170427-154809
 - [deleted]         CloudSlang-cloud-slang-211350341-20170315-135024
 - [deleted]         CloudSlang-cloud-slang-211350359-20170315-134528
 - [deleted]         CorfuDB-CorfuDB-205754176-20170227-120458
 - [deleted]         CorfuDB-CorfuDB-207497206-20170303-214112
 - [deleted]         Evolveum-midpoint-205752690-20170227-130937
 - [deleted]         Evolveum-midpoint-205785487-20170227-154252
 - [deleted]         Evolveum-midpoint-205800623-20170227-170157
 - [deleted]         Evolveum-midpoint-205827809-20170227-183730
 - [deleted]         Evolveum-midpoint-205833740-20170227-185730
 - [deleted]         Evolveum-midpoint-205995661-20170228-013226
 - [deleted]         Evolveum-midpoint-206994630-20170302-160728
 - [deleted]         Evolveum-midpoint-207292411-20170303-110537
 - [deleted]         Evolveum-midpoint-207295578-20170303-112107
 - [deleted]         Evolveum-midpoint-207310381-20170303-123303
 - [deleted]         Evolveum-midpoint-207318876-20170303-132426
 - [deleted]         Evolveum-midpoint-207366369-20170303-161535
 - [deleted]         Evolveum-midpoint-207400470-20170303-181322
 - [deleted]         Evolveum-midpoint-207514228-20170303-224205
 - [deleted]         Evolveum-midpoint-207517694-20170304-000910
 - [deleted]         Evolveum-midpoint-207566348-20170304-031847
 - [deleted]         Evolveum-midpoint-207793285-20170305-023332
 - [deleted]         Evolveum-midpoint-208162850-20170306-140142
 - [deleted]         Evolveum-midpoint-208214763-20170306-162520
 - [deleted]         Evolveum-midpoint-208253389-20170306-181329
 - [deleted]         Evolveum-midpoint-208371797-20170307-003443
 - [deleted]         Evolveum-midpoint-208406614-20170307-022326
 - [deleted]         Evolveum-midpoint-208523954-20170307-115701
 - [deleted]         Evolveum-midpoint-208667802-20170307-195259
 - [deleted]         Evolveum-midpoint-208676508-20170307-201923
 - [deleted]         Evolveum-midpoint-208687642-20170307-205803
 - [deleted]         Evolveum-midpoint-208888147-20170308-110825
 - [deleted]         Evolveum-midpoint-208969072-20170308-155420
 - [deleted]         Evolveum-midpoint-210640151-20170313-193257
 - [deleted]         Evolveum-midpoint-210952784-20170314-153215
 - [deleted]         Evolveum-midpoint-211399492-20170315-180313
 - [deleted]         Evolveum-midpoint-211684680-20170316-122326
 - [deleted]         Evolveum-midpoint-211685698-20170316-125717
 - [deleted]         Evolveum-midpoint-211797451-20170316-182447
 - [deleted]         Evolveum-midpoint-211877518-20170316-213101
 - [deleted]         Evolveum-midpoint-212045998-20170317-125039
 - [deleted]         Evolveum-midpoint-212262557-20170317-231453
 - [deleted]         Evolveum-midpoint-212318624-20170318-014439
 - [deleted]         Evolveum-midpoint-212318624-20170318-101522
 - [deleted]         Evolveum-midpoint-212438165-20170318-152458
 - [deleted]         Evolveum-midpoint-212707241-20170319-170208
 - [deleted]         Evolveum-midpoint-212731211-20170319-192504
 - [deleted]         Evolveum-midpoint-212739510-20170319-200653
 - [deleted]         Evolveum-midpoint-212741194-20170319-203415
 - [deleted]         Evolveum-midpoint-212790888-20170320-000744
 - [deleted]         Evolveum-midpoint-212849220-20170320-051140
 - [deleted]         Evolveum-midpoint-212909730-20170320-111706
 - [deleted]         Evolveum-midpoint-212914673-20170320-112821
 - [deleted]         Evolveum-midpoint-212918626-20170320-121136
 - [deleted]         Evolveum-midpoint-212919536-20170320-130317
 - [deleted]         Evolveum-midpoint-212962226-20170320-150138
 - [deleted]         Evolveum-midpoint-213365106-20170321-134141
 - [deleted]         Evolveum-midpoint-213478036-20170321-192001
 - [deleted]         Evolveum-midpoint-213632793-20170322-023143
 - [deleted]         Evolveum-midpoint-213661024-20170322-034658
 - [deleted]         Evolveum-midpoint-214236106-20170323-160244
 - [deleted]         Evolveum-midpoint-214246877-20170323-163717
 - [deleted]         Evolveum-midpoint-214282504-20170323-174403
 - [deleted]         Evolveum-midpoint-214290771-20170323-182245
 - [deleted]         Evolveum-midpoint-214292351-20170323-183932
 - [deleted]         Evolveum-midpoint-214575414-20170324-121111
 - [deleted]         Evolveum-midpoint-214599504-20170324-133533
 - [deleted]         Evolveum-midpoint-214620515-20170324-145943
 - [deleted]         Evolveum-midpoint-214620522-20170324-142550
 - [deleted]         Evolveum-midpoint-214682299-20170324-172336
 - [deleted]         Evolveum-midpoint-214711913-20170324-184012
 - [deleted]         Evolveum-midpoint-214883039-20170325-060912
 - [deleted]         Evolveum-midpoint-214904116-20170325-082806
 - [deleted]         Evolveum-midpoint-215479690-20170327-143142
 - [deleted]         Evolveum-midpoint-215596126-20170327-193500
 - [deleted]         Evolveum-midpoint-215671273-20170327-230354
 - [deleted]         Evolveum-midpoint-215852987-20170328-121304
 - [deleted]         Evolveum-midpoint-215900302-20170328-152320
 - [deleted]         Evolveum-midpoint-215966039-20170328-183732
 - [deleted]         Evolveum-midpoint-215966210-20170328-183701
 - [deleted]         Evolveum-midpoint-215989713-20170328-190917
 - [deleted]         Evolveum-midpoint-216044989-20170328-234056
 - [deleted]         Evolveum-midpoint-216045494-20170328-220043
 - [deleted]         Evolveum-midpoint-216045602-20170328-235622
 - [deleted]         Evolveum-midpoint-216047038-20170329-011028
 - [deleted]         Evolveum-midpoint-216156961-20170329-034025
 - [deleted]         Evolveum-midpoint-218003845-20170403-120441
 - [deleted]         Evolveum-midpoint-218009397-20170403-140335
 - [deleted]         Evolveum-midpoint-218024224-20170403-145546
 - [deleted]         Evolveum-midpoint-218079996-20170403-163319
 - [deleted]         Evolveum-midpoint-218093406-20170403-182541
 - [deleted]         Evolveum-midpoint-218106615-20170403-190139
 - [deleted]         Evolveum-midpoint-218133029-20170403-200443
 - [deleted]         Evolveum-midpoint-218177146-20170403-214707
 - [deleted]         Evolveum-midpoint-218198162-20170403-224352
 - [deleted]         Evolveum-midpoint-218515282-20170404-190926
 - [deleted]         Evolveum-midpoint-218855374-20170405-151016
 - [deleted]         Evolveum-midpoint-219239794-20170406-135244
 - [deleted]         FINRAOS-DataGenerator-207411960-20170303-171341
 - [deleted]         FasterXML-jackson-databind-208835510-20170308-042658
 - [deleted]         GwtMaterialDesign-gwt-material-205182085-20170225-030202
 - [deleted]         GwtMaterialDesign-gwt-material-207324015-20170303-121700
 - [deleted]         GwtMaterialDesign-gwt-material-219525509-20170407-040520
 - [deleted]         HubSpot-Singularity-208360384-20170306-225654
 - [deleted]         HubSpot-Singularity-209021127-20170308-181046
 - [deleted]         HubSpot-Singularity-211400103-20170315-165921
 - [deleted]         HubSpot-Singularity-211738750-20170316-143800
 - [deleted]         HubSpot-Singularity-212974650-20170320-143008
 - [deleted]         HubSpot-Singularity-213642102-20170322-011506
 - [deleted]         HubSpot-Singularity-219032562-20170405-224741
 - [deleted]         INL-BlackLab-212113775-20170317-141544
 - [deleted]         INL-BlackLab-212648945-20170319-105013
 - [deleted]         INL-BlackLab-214579765-20170324-103659
 - [deleted]         INRIA-spoon-189312463
 - [deleted]         INRIA-spoon-189312463-20170105-205226
 - [deleted]         INRIA-spoon-189312815
 - [deleted]         INRIA-spoon-189312815-20170105-205345
 - [deleted]         INRIA-spoon-189323953
 - [deleted]         INRIA-spoon-189323953-20170105-213122
 - [deleted]         INRIA-spoon-189327818
 - [deleted]         INRIA-spoon-189327818-20170105-214400
 - [deleted]         INRIA-spoon-189333299
 - [deleted]         INRIA-spoon-190753488-20170110-212537
 - [deleted]         INRIA-spoon-196757239-20170130-223204
 - [deleted]         INRIA-spoon-197103730-20170131-213542
 - [deleted]         MariaDB-mariadb-connector-j-207367958-20170303-161629
 - [deleted]         MariaDB-mariadb-connector-j-208739429-20170307-232302
 - [deleted]         MariaDB-mariadb-connector-j-209196135-20170309-044130
 - [deleted]         NanoHttpd-nanohttpd-212649623-20170319-105550
 - [deleted]         OpenGamma-Strata-216827458-20170330-183242
 - [deleted]         OpenGamma-Strata-216830409-20170330-183825
 - [deleted]         OpenGrok-OpenGrok-212903041-20170320-092944
 - [deleted]         OpenGrok-OpenGrok-218886420-20170405-155409
 - [deleted]         OpenGrok-OpenGrok-219197204-20170406-104955
 - [deleted]         OpenGrok-OpenGrok-219263134-20170406-144430
 - [deleted]         OpenGrok-OpenGrok-219279689-20170406-153028
 - [deleted]         OpenGrok-OpenGrok-219283755-20170406-154252
 - [deleted]         OpenGrok-OpenGrok-219347630-20170406-183034
 - [deleted]         OpenGrok-OpenGrok-219354349-20170406-184602
 - [deleted]         SonarSource-sonar-java-208620208-20170307-161905
 - [deleted]         SonarSource-sonar-java-208620216-20170307-162244
 - [deleted]         SonarSource-sonar-java-209195702-20170309-025203
 - [deleted]         SonarSource-sonar-java-209263273-20170309-090941
 - [deleted]         SonarSource-sonar-java-209263287-20170309-091802
 - [deleted]         SonarSource-sonar-java-209308779-20170309-121201
 - [deleted]         SonarSource-sonarqube-193107750-20170118-165606
 - [deleted]         SonarSource-sonarqube-194469867-20170123-134202
 - [deleted]         SonarSource-sonarqube-202571738-20170217-113928
 - [deleted]         SonarSource-sonarqube-204146224-20170222-120126
 - [deleted]         SonarSource-sonarqube-211292427-20170315-103553
 - [deleted]         SonarSource-sonarqube-211292498-20170315-103611
 - [deleted]         SonarSource-sonarqube-211297807-20170315-105301
 - [deleted]         SonarSource-sonarqube-211297819-20170315-105321
 - [deleted]         TridentSDK-TridentSDK-212322049-20170318-005112
 - [deleted]         abashev-vfs-s3-215694350-20170327-225705
 - [deleted]         abashev-vfs-s3-215694797-20170327-225828
 - [deleted]         addthis-stream-lib-212235144-20170317-200151
 - [deleted]         addthis-stream-lib-212239161-20170317-201258
 - [deleted]         aerogear-aerogear-unifiedpush-server-200927122-20170212-190613
 - [deleted]         aerogear-aerogear-unifiedpush-server-208917278-20170308-113718
 - [deleted]         aerogear-aerogear-unifiedpush-server-213439483-20170321-155930
 - [deleted]         aerogear-aerogear-unifiedpush-server-214237272-20170323-141949
 - [deleted]         airlift-airlift-196379527-20170129-180811
 - [deleted]         airlift-airlift-196380429-20170129-181409
 - [deleted]         airlift-airlift-196380882-20170129-181757
 - [deleted]         airlift-airlift-197393846-20170201-184711
 - [deleted]         airlift-airlift-209197266-20170309-025437
 - [deleted]         airlift-airlift-209201569-20170309-031839
 - [deleted]         alibaba-fastjson-208575264-20170307-135355
 - [deleted]         alibaba-fastjson-215132124-20170326-051934
 - [deleted]         alibaba-fastjson-215132864-20170326-052716
 - [deleted]         alibaba-fastjson-215172366-20170326-111606
 - [deleted]         alibaba-fastjson-215226088-20170326-163947
 - [deleted]         alibaba-fastjson-215862224-20170328-111638
 - [deleted]         alibaba-fastjson-215961117-20170328-163212
 - [deleted]         alibaba-fastjson-218438135-20170404-142954
 - [deleted]         alibaba-java-dns-cache-manipulator-205516306-20170226-151313
 - [deleted]         alibaba-java-dns-cache-manipulator-205518188-20170226-152222
 - [deleted]         andsel-moquette-209067760-20170308-191740
 - [deleted]         andsel-moquette-209082903-20170308-200854
 - [deleted]         andsel-moquette-212996691-20170320-151424
 - [deleted]         andsel-moquette-214059317-20170323-004949
 - [deleted]         antlr-antlr4-197828175-20170203-063429
 - [deleted]         antlr-antlr4-198185035-20170204-020614
 - [deleted]         antlr-antlr4-199330727-20170208-013417
 - [deleted]         antlr-antlr4-199471789-20170208-051128
 - [deleted]         antlr-antlr4-200174113-20170210-045813
 - [deleted]         antlr-antlr4-200177873-20170210-054334
 - [deleted]         antlr-antlr4-201014883-20170213-044721
 - [deleted]         antlr-antlr4-201459604-20170214-132158
 - [deleted]         antlr-antlr4-202346484-20170217-043114
 - [deleted]         antlr-antlr4-206808224-20170302-103933
 - [deleted]         antlr-antlr4-206837243-20170302-115252
 - [deleted]         antlr-antlr4-215738952-20170328-021448
 - [deleted]         apache-airavata-212287019-20170317-233022
 - [deleted]         apache-apex-core-211594182-20170316-033308
 - [deleted]         apache-apex-core-211962998-20170317-020403
 - [deleted]         apache-calcite-204043218-20170222-122556
 - [deleted]         apache-commons-math-199953586-20170209-145801
 - [deleted]         apache-commons-math-204972631-20170225-212450
 - [deleted]         apache-commons-math-205752074-20170227-124755
 - [deleted]         apache-commons-math-208020756-20170306-000225
 - [deleted]         apache-commons-math-208566163-20170307-164126
 - [deleted]         apache-commons-math-212742768-20170319-190905
 - [deleted]         apache-commons-math-213836438-20170322-150540
 - [deleted]         apache-flink-190922117-20170111-124636
 - [deleted]         apache-flink-191045719-20170111-215201
 - [deleted]         apache-flink-191125274-20170112-005203
 - [deleted]         apache-flink-191194068-20170112-060631
 - [deleted]         apache-flink-191287397-20170112-165630
 - [deleted]         apache-flink-191705763-20170113-201125
 - [deleted]         apache-flink-193017007-20170118-171624
 - [deleted]         apache-flink-193044380-20170118-184928
 - [deleted]         apache-flink-193116090-20170119-040841
 - [deleted]         apache-flink-193122689-20170119-041851
 - [deleted]         apache-flink-193434745-20170119-223931
 - [deleted]         apache-flink-194288201-20170122-223632
 - [deleted]         apache-flink-200227726-20170210-124758
 - [deleted]         apache-flink-200333901-20170210-201446
 - [deleted]         apache-flink-202204691-20170217-031804
 - [deleted]         apache-flink-204272289-20170223-105734
 - [deleted]         apache-flink-204504848-20170224-131757
 - [deleted]         apache-flink-204552114-20170224-193411
 - [deleted]         apache-flink-204568687-20170224-204243
 - [deleted]         apache-flink-204641257-20170225-042732
 - [deleted]         apache-flink-204676287-20170225-065127
 - [deleted]         apache-flink-204895104-20170225-180034
 - [deleted]         apache-flink-204900940-20170225-183937
 - [deleted]         apache-flink-205118260-20170226-091041
 - [deleted]         apache-flink-205225246-20170226-130240
 - [deleted]         apache-flink-205408027-20170226-153446
 - [deleted]         apache-flink-205542011-20170226-182038
 - [deleted]         apache-flink-205999673-20170228-075245
 - [deleted]         apache-flink-206668420-20170302-221016
 - [deleted]         apache-flink-207022501-20170304-051455
 - [deleted]         apache-flink-207032176-20170304-063412
 - [deleted]         apache-flink-207088291-20170304-093455
 - [deleted]         apache-flink-207223519-20170304-152209
 - [deleted]         apache-flink-207708816-20170305-100346
 - [deleted]         apache-flink-208162365-20170306-165052
 - [deleted]         apache-flink-208167525-20170306-173420
 - [deleted]         apache-flink-208185333-20170306-182734
 - [deleted]         apache-flink-208544976-20170307-161752
 - [deleted]         apache-flink-208549303-20170307-170505
 - [deleted]         apache-flink-208576719-20170307-221458
 - [deleted]         apache-flink-208828659-20170308-143010
 - [deleted]         apache-flink-210517454-20170313-161052
 - [deleted]         apache-flink-210980372-20170315-082038
 - [deleted]         apache-flink-210983308-20170315-085501
 - [deleted]         apache-flink-211000143-20170315-121812
 - [deleted]         apache-flink-211009187-20170315-124909
 - [deleted]         apache-flink-211029111-20170315-172805
 - [deleted]         apache-flink-211091996-20170315-185605
 - [deleted]         apache-flink-211290347-20170316-045241
 - [deleted]         apache-flink-211321661-20170316-102413
 - [deleted]         apache-flink-211328194-20170316-111222
 - [deleted]         apache-flink-211340849-20170316-122843
 - [deleted]         apache-flink-211786926-20170317-204733
 - [deleted]         apache-flink-211796961-20170317-212306
 - [deleted]         apache-flink-211806066-20170317-220241
 - [deleted]         apache-flink-212047749-20170318-054712
 - [deleted]         apache-flink-212066467-20170318-082153
 - [deleted]         apache-flink-212070460-20170318-084856
 - [deleted]         apache-flink-212148936-20170318-155733
 - [deleted]         apache-flink-212168880-20170318-172553
 - [deleted]         apache-flink-212868194-20170320-061443
 - [deleted]         apache-flink-212923151-20170320-125633
 - [deleted]         apache-flink-212947936-20170320-134540
 - [deleted]         apache-flink-213415549-20170321-234444
 - [deleted]         apache-flink-213418761-20170322-010034
 - [deleted]         apache-flink-213427497-20170322-032434
 - [deleted]         apache-flink-213432914-20170322-035843
 - [deleted]         apache-flink-213748515-20170322-125341
 - [deleted]         apache-flink-213751240-20170322-131253
 - [deleted]         apache-flink-213894506-20170323-010043
 - [deleted]         apache-flink-213926707-20170323-032709
 - [deleted]         apache-flink-214107315-20170323-092011
 - [deleted]         apache-flink-214150981-20170323-131023
 - [deleted]         apache-flink-214192391-20170323-175143
 - [deleted]         apache-flink-214201987-20170323-182233
 - [deleted]         apache-flink-214205676-20170323-185604
 - [deleted]         apache-flink-214207461-20170323-195837
 - [deleted]         apache-flink-214259690-20170324-003349
 - [deleted]         apache-flink-214260519-20170324-005300
 - [deleted]         apache-flink-214277926-20170324-011959
 - [deleted]         apache-flink-214291109-20170324-015353
 - [deleted]         apache-flink-214291990-20170324-021813
 - [deleted]         apache-flink-214347838-20170324-035302
 - [deleted]         apache-flink-214434301-20170324-041920
 - [deleted]         apache-flink-214489180-20170324-044734
 - [deleted]         apache-flink-214521263-20170324-065139
 - [deleted]         apache-flink-214521617-20170324-070520
 - [deleted]         apache-flink-214528872-20170324-073930
 - [deleted]         apache-flink-214551426-20170324-092502
 - [deleted]         apache-flink-214567431-20170324-102533
 - [deleted]         apache-flink-214601670-20170324-140425
 - [deleted]         apache-flink-214606831-20170324-144746
 - [deleted]         apache-flink-214912588-20170325-093126
 - [deleted]         apache-flink-215182378-20170326-130208
 - [deleted]         apache-flink-215462358-20170327-124644
 - [deleted]         apache-flink-215824541-20170328-103834
 - [deleted]         apache-flink-215873559-20170328-141950
 - [deleted]         apache-flink-215931391-20170328-163155
 - [deleted]         apache-flink-215938437-20170328-174714
 - [deleted]         apache-flink-216176138-20170329-041516
 - [deleted]         apache-flink-216202865-20170329-073319
 - [deleted]         apache-flink-216646099-20170330-101000
 - [deleted]         apache-flink-216718350-20170330-145834
 - [deleted]         apache-flink-216780021-20170330-175510
 - [deleted]         apache-flink-216792045-20170330-191201
 - [deleted]         apache-flink-216882305-20170330-213209
 - [deleted]         apache-flink-218424237-20170404-151806
 - [deleted]         apache-flink-218604174-20170404-215709
 - [deleted]         apache-flink-218618187-20170404-224931
 - [deleted]         apache-flink-219058226-20170406-031434
 - [deleted]         apache-flink-219110467-20170406-054020
 - [deleted]         apache-flink-219134183-20170406-061559
 - [deleted]         apache-flink-219153528-20170406-091728
 - [deleted]         apache-flink-219154203-20170406-093421
 - [deleted]         apache-flink-219180341-20170406-115202
 - [deleted]         apache-flink-219200479-20170406-123059
 - [deleted]         apache-flink-219250671-20170406-182716
 - [deleted]         apache-flink-219266238-20170406-193734
 - [deleted]         apache-flink-219300924-20170406-213158
 - [deleted]         apache-flink-219422931-20170407-002544
 - [deleted]         apache-flink-219445248-20170407-010859
 - [deleted]         apache-flink-219449950-20170407-014834
 - [deleted]         apache-flink-219554823-20170407-080202
 - [deleted]         apache-flink-219589852-20170407-111057
 - [deleted]         apache-flink-239296512-20170604-162518_bugonly
 - [deleted]         apache-flink-239304084-20170604-173003_bugonly
 - [deleted]         apache-httpclient-212432232-20170318-130837
 - [deleted]         apache-incubator-metron-209066101-20170309-081620
 - [deleted]         apache-incubator-metron-212735000-20170319-184957
 - [deleted]         apache-incubator-metron-213919294-20170322-191836
 - [deleted]         apache-incubator-metron-214250605-20170323-170209
 - [deleted]         apache-incubator-metron-214657176-20170324-152937
 - [deleted]         apache-incubator-metron-214684324-20170324-165218
 - [deleted]         apache-incubator-metron-214708772-20170324-180642
 - [deleted]         apache-incubator-samoa-212987619-20170320-145250
 - [deleted]         apache-jackrabbit-oak-196724309-20170130-221330
 - [deleted]         apache-jackrabbit-oak-201913224-20170216-023442
 - [deleted]         apache-jackrabbit-oak-208203777-20170306-180053
 - [deleted]         apache-jackrabbit-oak-208224009-20170306-184316
 - [deleted]         apache-jackrabbit-oak-208870916-20170308-202649
 - [deleted]         apache-jackrabbit-oak-208879893-20170308-221231
 - [deleted]         apache-jackrabbit-oak-208892704-20170308-225739
 - [deleted]         apache-jackrabbit-oak-208925904-20170309-015100
 - [deleted]         apache-jackrabbit-oak-208942133-20170309-030723
 - [deleted]         apache-jackrabbit-oak-209017212-20170309-062409
 - [deleted]         apache-jackrabbit-oak-209039647-20170309-065355
 - [deleted]         apache-jackrabbit-oak-210882081-20170314-114510
 - [deleted]         apache-jackrabbit-oak-211733071-20170316-143055
 - [deleted]         apache-jackrabbit-oak-213509159-20170321-202842
 - [deleted]         apache-jackrabbit-oak-216673233-20170330-121524
 - [deleted]         apache-jackrabbit-oak-216692508-20170330-122157
 - [deleted]         apache-jackrabbit-oak-216709064-20170330-131206
 - [deleted]         apache-jackrabbit-oak-226381342-20170427-150102_bugonly
 - [deleted]         apache-logging-log4j2-194118581-20170122-011245
 - [deleted]         apache-logging-log4j2-194975442-20170124-225703
 - [deleted]         apache-nifi-200111447-20170210-052737
 - [deleted]         apache-nifi-201023267-20170213-055051
 - [deleted]         apache-nifi-201025647-20170213-055648
 - [deleted]         apache-nifi-201135063-20170213-170921
 - [deleted]         apache-nifi-201392211-20170214-105009
 - [deleted]         apache-nifi-201438867-20170214-145206
 - [deleted]         apache-nifi-201487601-20170214-173053
 - [deleted]         apache-nifi-201535624-20170214-200545
 - [deleted]         apache-nifi-201564948-20170214-222944
 - [deleted]         apache-nifi-201566738-20170214-225905
 - [deleted]         apache-nifi-201661269-20170215-082850
 - [deleted]         apache-nifi-201748115-20170215-160954
 - [deleted]         apache-nifi-201750218-20170215-163123
 - [deleted]         apache-nifi-201776387-20170215-174505
 - [deleted]         apache-nifi-201780512-20170215-182130
 - [deleted]         apache-nifi-201873488-20170216-011245
 - [deleted]         apache-nifi-201892644-20170216-020918
 - [deleted]         apache-nifi-202042710-20170216-085521
 - [deleted]         apache-nifi-202046811-20170216-092907
 - [deleted]         apache-nifi-202078002-20170216-144951
 - [deleted]         apache-nifi-204702615-20170225-000827
 - [deleted]         apache-nifi-204816771-20170225-112208
 - [deleted]         apache-nifi-204839369-20170225-115746
 - [deleted]         apache-nifi-204888594-20170225-164823
 - [deleted]         apache-nifi-204992328-20170225-223033
 - [deleted]         apache-nifi-204993745-20170225-223732
 - [deleted]         apache-nifi-204999434-20170225-224147
 - [deleted]         apache-nifi-205118562-20170226-062024
 - [deleted]         apache-nifi-205130584-20170226-074051
 - [deleted]         apache-nifi-205266193-20170226-124521
 - [deleted]         apache-nifi-205504490-20170226-165101
 - [deleted]         apache-nifi-205814069-20170227-181134
 - [deleted]         apache-nifi-205819020-20170227-181947
 - [deleted]         apache-nifi-205866781-20170227-201135
 - [deleted]         apache-nifi-205878182-20170227-205848
 - [deleted]         apache-nifi-205887744-20170227-223855
 - [deleted]         apache-nifi-205929383-20170228-034647
 - [deleted]         apache-nifi-205988374-20170228-070906
 - [deleted]         apache-nifi-207669108-20170305-081017
 - [deleted]         apache-nifi-207909347-20170305-160509
 - [deleted]         apache-nifi-207909949-20170305-160604
 - [deleted]         apache-nifi-207911275-20170305-161557
 - [deleted]         apache-nifi-208059366-20170306-043708
 - [deleted]         apache-nifi-208546007-20170307-160459
 - [deleted]         apache-nifi-208704498-20170308-044616
 - [deleted]         apache-nifi-208752735-20170308-073606
 - [deleted]         apache-nifi-208754954-20170308-080507
 - [deleted]         apache-nifi-208787855-20170308-113128
 - [deleted]         apache-nifi-208807295-20170308-124002
 - [deleted]         apache-nifi-208808780-20170308-124332
 - [deleted]         apache-nifi-208949996-20170309-040308
 - [deleted]         apache-nifi-209061021-20170309-081025
 - [deleted]         apache-nifi-209123323-20170309-115354
 - [deleted]         apache-nifi-210533688-20170313-132707
 - [deleted]         apache-nifi-210574779-20170313-154905
 - [deleted]         apache-nifi-210575411-20170313-154814
 - [deleted]         apache-nifi-210619043-20170313-175946
 - [deleted]         apache-nifi-210620323-20170313-180805
 - [deleted]         apache-nifi-210625034-20170313-182219
 - [deleted]         apache-nifi-210625554-20170313-183448
 - [deleted]         apache-nifi-211349078-20170315-175136
 - [deleted]         apache-nifi-211652813-20170316-095702
 - [deleted]         apache-nifi-212097821-20170317-141145
 - [deleted]         apache-nifi-212236920-20170317-204427
 - [deleted]         apache-nifi-212270585-20170317-225009
 - [deleted]         apache-nifi-212991879-20170320-153123
 - [deleted]         apache-nifi-213000648-20170320-160232
 - [deleted]         apache-nifi-213448560-20170321-183037
 - [deleted]         apache-nifi-213478169-20170321-191227
 - [deleted]         apache-nifi-213501832-20170321-202517
 - [deleted]         apache-nifi-213541346-20170321-214959
 - [deleted]         apache-nifi-213589582-20170321-232737
 - [deleted]         apache-nifi-213683477-20170322-050743
 - [deleted]         apache-nifi-213760190-20170322-112318
 - [deleted]         apache-nifi-213855785-20170322-162440
 - [deleted]         apache-nifi-213887636-20170322-173349
 - [deleted]         apache-nifi-214059741-20170323-013535
 - [deleted]         apache-nifi-214325242-20170323-192941
 - [deleted]         apache-nifi-214452495-20170324-002314
 - [deleted]         apache-nifi-214593738-20170324-120451
 - [deleted]         apache-nifi-215198850-20170326-144804
 - [deleted]         apache-nifi-215240413-20170326-182402
 - [deleted]         apache-nifi-215523931-20170327-160635
 - [deleted]         apache-nifi-215538059-20170327-164723
 - [deleted]         apache-nifi-215692192-20170328-001417
 - [deleted]         apache-nifi-215729160-20170328-012721
 - [deleted]         apache-nifi-216091910-20170328-232038
 - [deleted]         apache-nifi-216889159-20170330-213829
 - [deleted]         apache-nifi-218141081-20170403-191734
 - [deleted]         apache-nifi-218167397-20170403-203912
 - [deleted]         apache-nifi-218182547-20170403-212016
 - [deleted]         apache-nifi-218645937-20170405-002031
 - [deleted]         apache-nifi-218963707-20170405-194528
 - [deleted]         apache-nifi-219079586-20170406-013156
 - [deleted]         apache-nifi-219398547-20170406-212219

**Comment by monperrus** [comment]
excellent, thanks
