### ISSUE TITLE
Improve and release maven-repair

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#301]
inspired from `https://github.com/Spirals-Team/npefix-maven`

(related and maybe better than #75)

**Comment by surli** [comment]
WiP in https://github.com/surli/nopol-maven

**Comment by surli** [comment]
Actually it's now on https://github.com/Spirals-Team/maven-repair

**Comment by surli** [comment]
Actually it's deployed on snapshot repo, it should be enough for now.

**Comment by monperrus** [comment]
Where is the code of maven-repair?

--Martin

**Comment by surli** [comment]
https://github.com/Spirals-Team/maven-repair
