### ISSUE TITLE
Sep 20: we have far too many NOTBUILDABLE

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#344]
even on Inria/Spoon

**Comment by surli** [comment]
Related to MavenModelResolver, fixed.

**Comment by monperrus** [comment]
> Related to MavenModelResolver, fixed.
>
>
transient error? cause?

**Comment by surli** [comment]
> transient error? cause?

MavenModelResolver is in charge for downloading distant parent pom (like oss parent pom in Spoon), but apparently it wasn't checking the request response status and so it recorded even 404 messages as a parent pom, and even worse: I wasn't leaving the function after the first download test (we check the parent pom against some mirrors), then even if the first request was good, it was downloading all parent pom from all mirrors...
