### ISSUE TITLE
Remove notification email adresses from .travis.yml

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#368]
Before pushing a project, take care in removing notification section from .travis.yml of projects or project's owner might receive notification emails

**Comment by monperrus** [comment]
Interesting! Did you get a complaint?

**Comment by surli** [comment]
Yep: https://github.com/Spirals-Team/librepair-experiments/issues/1

**Comment by monperrus** [comment]
This could be a fun recommandation for the paper :-)

**Comment by surli** [comment]
Done in #390
