### ISSUE TITLE
don't push surli/failingproject to librepair-experiments and to mongodb

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#371]
and remove the past branches

**Comment by surli** [comment]
For the record the following branches have been deleted: 

- [deleted]                   Asqatasun-Asqatasun-278769188-20170922-223556_bugonly
 - [deleted]                   Asqatasun-Asqatasun-278770625-20170922-224024_bugonly
 - [deleted]                   Asqatasun-Asqatasun-278907173-20170923-120737_bugonly
 - [deleted]                   Asqatasun-Asqatasun-278964470-20170923-171857_bugonly
 - [deleted]                   apache-storm-193103183-20170118-174149
 - [deleted]                   apache-storm-193518363-20170119-214846
 - [deleted]                   apache-storm-193754517-20170120-150854
 - [deleted]                   apache-storm-194375544-20170123-070017
 - [deleted]                   apache-storm-194806295-20170124-134541
 - [deleted]                   apache-storm-196722507-20170130-223601
 - [deleted]                   apache-storm-196832023-20170131-051910
 - [deleted]                   apache-storm-196861133-20170131-082854
 - [deleted]                   apache-storm-196887789-20170131-103713
 - [deleted]                   apache-storm-197100686-20170201-150336
 - [deleted]                   apache-storm-197172626-20170201-174659
 - [deleted]                   apache-storm-197175916-20170201-175602
 - [deleted]                   apache-storm-197341230-20170202-000646
 - [deleted]                   apache-storm-197441810-20170202-020842
 - [deleted]                   apache-storm-197444884-20170202-021358
 - [deleted]                   apache-storm-197567465-20170202-095315
 - [deleted]                   apache-storm-197679148-20170202-161455
 - [deleted]                   apache-storm-197700758-20170202-172215
 - [deleted]                   apache-storm-197846085-20170203-004827
 - [deleted]                   apache-storm-197848897-20170203-010448
 - [deleted]                   apache-storm-197852172-20170203-011307
 - [deleted]                   apache-storm-197858121-20170203-014714
 - [deleted]                   apache-storm-197858209-20170203-014326
 - [deleted]                   apache-storm-198203561-20170204-191726
 - [deleted]                   apache-storm-198221062-20170204-200930
 - [deleted]                   apache-storm-198233586-20170204-204542
 - [deleted]                   apache-storm-198236617-20170204-203306
 - [deleted]                   apache-storm-198238717-20170204-205558
 - [deleted]                   apache-storm-198239348-20170204-205205
 - [deleted]                   apache-storm-198242685-20170204-210258
 - [deleted]                   apache-storm-198274550-20170204-215431
 - [deleted]                   apache-storm-199042362-20170207-045518
 - [deleted]                   apache-storm-199055219-20170207-061318
 - [deleted]                   apache-storm-199095117-20170207-090630
 - [deleted]                   apache-storm-199135301-20170207-110016
 - [deleted]                   apache-storm-199396786-20170208-025107
 - [deleted]                   apache-storm-199398879-20170208-025940
 - [deleted]                   apache-storm-199485106-20170208-090625
 - [deleted]                   apache-storm-199500673-20170208-095652
 - [deleted]                   apache-storm-199761509-20170209-051816
 - [deleted]                   apache-storm-199766699-20170209-052747
 - [deleted]                   apache-storm-200429403-20170211-003053
 - [deleted]                   apache-storm-200487417-20170211-042459
 - [deleted]                   apache-storm-200939496-20170212-203711
 - [deleted]                   apache-storm-204523109-20170224-151603
 - [deleted]                   apache-storm-204940606-20170225-205350
 - [deleted]                   apache-storm-205066464-20170226-021146
 - [deleted]                   apache-storm-205070881-20170226-023412
 - [deleted]                   apache-storm-205194074-20170226-113302
 - [deleted]                   apache-storm-205315975-20170226-131948
 - [deleted]                   apache-struts-197826262-20170202-230511
 - [deleted]                   apache-struts-214130454-20170323-071715
 - [deleted]                   arquillian-arquillian-cube-210854946-20170314-085750
 - [deleted]                   atomix-copycat-199491608-20170208-044754
 - [deleted]                   atomix-copycat-199716416-20170208-190316
 - [deleted]                   atomix-copycat-199834717-20170209-014841
 - [deleted]                   atomix-copycat-200547929-20170211-010505
 - [deleted]                   atomix-copycat-200565958-20170211-030612
 - [deleted]                   atomix-copycat-201683947-20170214-223439
 - [deleted]                   atomix-copycat-202442498-20170217-003130
 - [deleted]                   atomix-copycat-213778603-20170322-115118
 - [deleted]                   aws-aws-dynamodb-session-tomcat-215644226-20170327-203243
 - [deleted]                   aws-aws-dynamodb-session-tomcat-219459358-20170406-234008
 - [deleted]                   aws-aws-dynamodb-session-tomcat-219512331-20170407-024603
 - [deleted]                   aws-aws-sdk-java-208357316-20170306-223402
 - [deleted]                   b3log-symphony-207681938-20170304-152037
 - [deleted]                   basho-riak-java-client-212113649-20170317-142028
 - [deleted]                   biojava-biojava-213663692-20170322-023637
 - [deleted]                   biojava-biojava-213888034-20170322-165833
 - [deleted]                   biojava-biojava-213915849-20170322-175543
 - [deleted]                   biojava-biojava-213927800-20170322-182417
 - [deleted]                   biojava-biojava-218995836-20170405-204303
 - [deleted]                   biojava-biojava-219090318-20170406-014207
 - [deleted]                   bonigarcia-webdrivermanager-208554287-20170307-142401
 - [deleted]                   bonigarcia-webdrivermanager-208554287-20170308-113442
 - [deleted]                   bonigarcia-webdrivermanager-209028291-20170308-172232
 - [deleted]                   bonigarcia-webdrivermanager-209029198-20170308-172437
 - [deleted]                   bonigarcia-webdrivermanager-209029219-20170308-172436
 - [deleted]                   bonigarcia-webdrivermanager-216650353-20170330-092759
 - [deleted]                   boonproject-boon-215105925-20170326-010314
 - [deleted]                   brettwooldridge-HikariCP-193068916-20170118-150123
 - [deleted]                   brettwooldridge-HikariCP-202380908-20170216-210535
 - [deleted]                   checkstyle-checkstyle-192476317-20170116-213120
 - [deleted]                   checkstyle-checkstyle-192477469-20170116-214655
 - [deleted]                   checkstyle-checkstyle-192478604-20170116-220847
 - [deleted]                   checkstyle-checkstyle-192481798-20170116-223910
 - [deleted]                   checkstyle-checkstyle-192483964-20170116-230136
 - [deleted]                   checkstyle-checkstyle-199753661-20170208-230115
 - [deleted]                   checkstyle-checkstyle-206959707-20170302-124609
 - [deleted]                   checkstyle-checkstyle-206960202-20170302-130125
 - [deleted]                   checkstyle-checkstyle-207624331-20170304-090709
 - [deleted]                   checkstyle-checkstyle-207624713-20170304-091522
 - [deleted]                   checkstyle-checkstyle-207695632-20170304-164955
 - [deleted]                   checkstyle-checkstyle-207733142-20170304-195106
 - [deleted]                   checkstyle-checkstyle-207880921-20170305-131938
 - [deleted]                   checkstyle-checkstyle-207954665-20170305-191708
 - [deleted]                   checkstyle-checkstyle-208537959-20170307-121146
 - [deleted]                   checkstyle-checkstyle-208877008-20170308-094033
 - [deleted]                   checkstyle-checkstyle-208880317-20170308-101235
 - [deleted]                   checkstyle-checkstyle-208912166-20170308-122332
 - [deleted]                   checkstyle-checkstyle-209271671-20170309-100327
 - [deleted]                   checkstyle-checkstyle-209276461-20170309-102854
 - [deleted]                   checkstyle-checkstyle-210588089-20170313-165558
 - [deleted]                   checkstyle-checkstyle-210812908-20170314-044920
 - [deleted]                   checkstyle-checkstyle-210814259-20170314-050019
 - [deleted]                   checkstyle-checkstyle-211649924-20170316-092014
 - [deleted]                   checkstyle-checkstyle-211652635-20170316-093157
 - [deleted]                   checkstyle-checkstyle-211664824-20170316-103533
 - [deleted]                   checkstyle-checkstyle-212270058-20170317-222151
 - [deleted]                   checkstyle-checkstyle-212387336-20170318-080626
 - [deleted]                   checkstyle-checkstyle-212451643-20170318-151828
 - [deleted]                   checkstyle-checkstyle-212456910-20170318-154858
 - [deleted]                   checkstyle-checkstyle-212497487-20170318-221613
 - [deleted]                   checkstyle-checkstyle-212530362-20170318-230915
 - [deleted]                   checkstyle-checkstyle-212539253-20170318-234658
 - [deleted]                   checkstyle-checkstyle-212574373-20170319-020749
 - [deleted]                   checkstyle-checkstyle-212666610-20170319-125251
 - [deleted]                   checkstyle-checkstyle-212676190-20170319-144421
 - [deleted]                   checkstyle-checkstyle-212722232-20170319-184140
 - [deleted]                   checkstyle-checkstyle-212737532-20170319-193329
 - [deleted]                   checkstyle-checkstyle-212840648-20170320-025231
 - [deleted]                   checkstyle-checkstyle-212844989-20170320-031146
 - [deleted]                   checkstyle-checkstyle-212862848-20170320-051342
 - [deleted]                   checkstyle-checkstyle-212868430-20170320-055310
 - [deleted]                   checkstyle-checkstyle-213360399-20170321-123346
 - [deleted]                   checkstyle-checkstyle-213373239-20170321-131110
 - [deleted]                   checkstyle-checkstyle-214124525-20170323-064616
 - [deleted]                   checkstyle-checkstyle-214245028-20170323-151014
 - [deleted]                   checkstyle-checkstyle-214245354-20170323-155422
 - [deleted]                   checkstyle-checkstyle-214646486-20170324-145118
 - [deleted]                   checkstyle-checkstyle-214652746-20170324-154304
 - [deleted]                   checkstyle-checkstyle-214799953-20170324-221042
 - [deleted]                   checkstyle-checkstyle-214830072-20170324-234836
 - [deleted]                   checkstyle-checkstyle-215089128-20170325-235529
 - [deleted]                   checkstyle-checkstyle-215162984-20170326-101740
 - [deleted]                   checkstyle-checkstyle-215243227-20170326-181105
 - [deleted]                   checkstyle-checkstyle-215244346-20170326-182311
 - [deleted]                   checkstyle-checkstyle-215295574-20170326-221258
 - [deleted]                   checkstyle-checkstyle-215306167-20170326-230212
 - [deleted]                   checkstyle-checkstyle-215312131-20170326-233242
 - [deleted]                   checkstyle-checkstyle-215315418-20170326-234506
 - [deleted]                   checkstyle-checkstyle-215317834-20170326-235732
 - [deleted]                   checkstyle-checkstyle-215318055-20170327-000726
 - [deleted]                   checkstyle-checkstyle-215319880-20170327-001848
 - [deleted]                   checkstyle-checkstyle-215629935-20170327-202242
 - [deleted]                   checkstyle-checkstyle-215761434-20170328-031643
 - [deleted]                   checkstyle-checkstyle-215762580-20170328-032604
 - [deleted]                   checkstyle-checkstyle-215981864-20170328-174308
 - [deleted]                   checkstyle-checkstyle-216182945-20170329-043415
 - [deleted]                   checkstyle-checkstyle-216183270-20170329-044917
 - [deleted]                   checkstyle-checkstyle-218236730-20170403-233115
 - [deleted]                   checkstyle-checkstyle-218241538-20170403-235137
 - [deleted]                   checkstyle-checkstyle-218546395-20170404-194336
 - [deleted]                   checkstyle-checkstyle-218634143-20170404-234356
 - [deleted]                   checkstyle-checkstyle-218876837-20170405-164817
 - [deleted]                   checkstyle-checkstyle-218932172-20170405-184931
 - [deleted]                   chocoteam-choco-solver-189515983-20170106-143918
 - [deleted]                   chocoteam-choco-solver-205812338-20170227-155836
 - [deleted]                   chocoteam-choco-solver-205813984-20170227-155809
 - [deleted]                   chocoteam-choco-solver-212138724-20170317-154621
 - [deleted]                   chocoteam-choco-solver-216816886-20170330-181739
 - [deleted]                   chocoteam-choco-solver-218795390-20170405-105829
 - [deleted]                   chocoteam-choco-solver-218795801-20170405-110010
 - [deleted]                   chocoteam-choco-solver-218822836-20170405-123141
 - [deleted]                   chocoteam-choco-solver-218884446-20170405-160401
 - [deleted]                   chocoteam-choco-solver-218887888-20170405-161331
 - [deleted]                   chocoteam-choco-solver-218910499-20170405-170821
 - [deleted]                   dangdangdotcom-elastic-job-192663753-20170117-131436
 - [deleted]                   dangdangdotcom-elastic-job-192885265-20170118-005219
 - [deleted]                   dangdangdotcom-elastic-job-192895272-20170118-020357
 - [deleted]                   dangdangdotcom-elastic-job-192909556-20170118-024521
 - [deleted]                   dangdangdotcom-elastic-job-192910999-20170118-025849
 - [deleted]                   dangdangdotcom-elastic-job-192962731-20170118-090040
 - [deleted]                   dangdangdotcom-elastic-job-192968105-20170118-093248
 - [deleted]                   dangdangdotcom-elastic-job-193311170-20170119-084535
 - [deleted]                   dangdangdotcom-elastic-job-193313090-20170119-085835
 - [deleted]                   dangdangdotcom-elastic-job-193672591-20170120-085545
 - [deleted]                   dangdangdotcom-elastic-job-193673153-20170120-085700
 - [deleted]                   dangdangdotcom-elastic-job-193677753-20170120-091750
 - [deleted]                   dangdangdotcom-elastic-job-205464653-20170226-101235
 - [deleted]                   dangdangdotcom-elastic-job-205792021-20170227-145201
 - [deleted]                   dangdangdotcom-elastic-job-212142060-20170317-154542
 - [deleted]                   dangdangdotcom-elastic-job-212377717-20170318-062549
 - [deleted]                   dangdangdotcom-elastic-job-214508997-20170324-042314
 - [deleted]                   dangdangdotcom-elastic-job-214539417-20170324-072825
 - [deleted]                   dangdangdotcom-elastic-job-214585936-20170324-110205
 - [deleted]                   dangdangdotcom-elastic-job-214595950-20170324-113743
 - [deleted]                   dangdangdotcom-elastic-job-214599065-20170324-120056
 - [deleted]                   dangdangdotcom-elastic-job-214601723-20170324-115927
 - [deleted]                   dangdangdotcom-elastic-job-214601723-20170324-151043
 - [deleted]                   dangdangdotcom-elastic-job-216640359-20170330-084103
 - [deleted]                   dangdangdotcom-elastic-job-216693237-20170330-120053
 - [deleted]                   dangdangdotcom-elastic-job-216760273-20170330-155417
 - [deleted]                   dangdangdotcom-elastic-job-216791187-20170330-171821
 - [deleted]                   dangdangdotcom-elastic-job-216793746-20170330-171758
 - [deleted]                   dangdangdotcom-elastic-job-216807187-20170330-174329
 - [deleted]                   dangdangdotcom-elastic-job-218313828-20170404-050940
 - [deleted]                   dangdangdotcom-elastic-job-218716731-20170405-041714
 - [deleted]                   dangdangdotcom-elastic-job-218799807-20170405-110633
 - [deleted]                   dangdangdotcom-elastic-job-218802590-20170405-111418
 - [deleted]                   dangdangdotcom-elastic-job-218812031-20170405-114523
 - [deleted]                   surli-failingProject-208897537-20170308-090715
 - [deleted]                   surli-failingProject-210040393-20170311-123815
 - [deleted]                   surli-failingProject-210276803-20170312-154156
 - [deleted]                   surli-failingProject-210544091-20170313-124003
 - [deleted]                   surli-failingProject-210604815-20170313-154157
 - [deleted]                   surli-failingProject-210992329-20170314-154524
 - [deleted]                   surli-failingProject-226068415-20170426-180414_bugonly
 - [deleted]                   surli-failingProject-227634321-20170501-180708_bugonly
 - [deleted]                   surli-failingProject-282833488-20171003-192251_bugonly
 - [deleted]                   surli-failingProject-283293305-20171004-192320_bugonly
 - [deleted]                   surli-failingProject-283721991-20171005-162831_bugonly
 - [deleted]                   surli-failingProject-283805075-20171005-192407_bugonly
 - [deleted]                   surli-failingProject-284234296-20171006-162732_bugonly
 - [deleted]                   surli-failingProject-284311295-20171006-192505_bugonly
 - [deleted]                   surli-failingProject-284682261-20171007-162746_bugonly
 - [deleted]                   surli-failingProject-284740098-20171007-192529_bugonly
 - [deleted]                   surli-failingProject-285085811-20171008-162856_bugonly
 - [deleted]                   surli-failingProject-285145253-20171008-192621_bugonly
 - [deleted]                   surli-failingProject-285701913-20171009-192640_bugonly
 - [deleted]                   surli-failingProject-286144144-20171010-192751_bugonly
 - [deleted]                   surli-failingProject-286628283-20171011-192736_bugonly
 - [deleted]                   surli-failingProject-287071689-20171012-162836_bugonly
 - [deleted]                   surli-failingProject-287158043-20171012-192811_bugonly
 - [deleted]                   surli-failingProject-287587157-20171013-162943_bugonly
 - [deleted]                   surli-failingProject-287656547-20171013-192841_bugonly
 - [deleted]                   surli-failingProject-287937212-20171014-163126_bugonly
 - [deleted]                   surli-failingProject-287980125-20171014-192834_bugonly
 - [deleted]                   surli-failingProject-288256596-20171015-192915_bugonly
 - [deleted]                   surli-failingProject-288589807-20171016-163105_bugonly
 - [deleted]                   surli-failingProject-288671374-20171016-193016_bugonly
 - [deleted]                   surli-failingProject-289141910-20171017-193044_bugonly
 - [deleted]                   surli-failingProject-289534825-20171018-163125_bugonly
 - [deleted]                   surli-failingProject-289612645-20171018-193146_bugonly
 - [deleted]                   surli-failingProject-290013072-20171019-163140_bugonly
 - [deleted]                   surli-failingProject-290100015-20171019-193136_bugonly
 - [deleted]                   surli-failingProject-290481549-20171020-163156_bugonly
 - [deleted]                   surli-failingProject-290555441-20171020-193131_bugonly
 - [deleted]                   surli-failingProject-290839202-20171021-163215_bugonly
 - [deleted]                   surli-failingProject-290886857-20171021-193139_bugonly
 - [deleted]                   surli-failingProject-291144170-20171022-163247_bugonly
 - [deleted]                   surli-failingProject-291196432-20171022-193238_bugonly
 - [deleted]                   surli-failingProject-291576929-20171023-163322_bugonly
 - [deleted]                   surli-failingProject-291663427-20171023-193310_bugonly
 - [deleted]                   surli-failingProject-292110855-20171024-163400_bugonly
 - [deleted]                   surli-failingProject-292203303-20171024-193403_bugonly
 - [deleted]                   surli-failingProject-292648109-20171025-163439_bugonly
 - [deleted]                   surli-failingProject-292735472-20171025-193418_bugonly
 - [deleted]                   surli-failingProject-293183113-20171026-163440_bugonly
 - [deleted]                   surli-failingProject-293269243-20171026-193905_bugonly
 - [deleted]                   surli-failingProject-293794937-20171027-193536_bugonly
 - [deleted]                   surli-failingProject-294134035-20171028-163537_bugonly
 - [deleted]                   surli-failingProject-294184270-20171028-193723_bugonly
 - [deleted]                   surli-failingProject-294464442-20171029-153608_bugonly
 - [deleted]                   surli-failingProject-294518912-20171029-184141_bugonly
 - [deleted]                   surli-failingProject-294888739-20171030-153705_bugonly
 - [deleted]                   surli-failingProject-294976107-20171030-183719_bugonly
 - [deleted]                   surli-failingProject-295324787-20171031-153701_bugonly
 - [deleted]                   surli-failingProject-295406973-20171031-184708_bugonly
 - [deleted]                   surli-failingProject-295779130-20171101-153721_bugonly
 - [deleted]                   surli-failingProject-295865401-20171101-183919_bugonly
 - [deleted]                   surli-failingProject-296297430-20171102-153802_bugonly
 - [deleted]                   surli-failingProject-296389418-20171102-184356_bugonly
 - [deleted]                   surli-failingProject-296813645-20171103-153818_bugonly
 - [deleted]                   surli-failingProject-296903958-20171103-184221_bugonly
 - [deleted]                   surli-failingProject-297224931-20171104-153844_bugonly
 - [deleted]                   surli-failingProject-297280213-20171104-184041_bugonly
 - [deleted]                   surli-failingProject-297566826-20171105-153902_bugonly
 - [deleted]                   surli-failingProject-297626631-20171105-184203_bugonly
 - [deleted]                   surli-failingProject-298018056-20171106-153950_bugonly
 - [deleted]                   surli-failingProject-298110484-20171106-184214_bugonly
 - [deleted]                   surli-failingProject-298579095-20171107-154033_bugonly
 - [deleted]                   surli-failingProject-298669866-20171107-184210_bugonly
 - [deleted]                   surli-failingProject-299132479-20171108-154059_bugonly
 - [deleted]                   surli-failingProject-299221501-20171108-184350_bugonly
 - [deleted]                   surli-failingProject-299670968-20171109-154200_bugonly
 - [deleted]                   surli-failingProject-299768974-20171109-184335_bugonly
 - [deleted]                   surli-failingProject-300195928-20171110-154558_bugonly
 - [deleted]                   surli-failingProject-300280966-20171110-184353_bugonly
 - [deleted]                   surli-failingProject-300667631-20171111-184410_bugonly
 - [deleted]                   surli-failingProject-300962742-20171112-154233_bugonly
 - [deleted]                   surli-failingProject-301017750-20171112-184534_bugonly
 - [deleted]                   surli-failingProject-301432689-20171113-154412_bugonly
 - [deleted]                   surli-failingProject-301525077-20171113-184539_bugonly
 - [deleted]                   surli-failingProject-302060322-20171114-184625_bugonly
 - [deleted]                   surli-failingProject-302516793-20171115-154415_bugonly
 - [deleted]                   surli-failingProject-302534029-20171115-161727_bugonly
 - [deleted]                   surli-failingProject-302537218-20171115-162430_bugonly
 - [deleted]                   surli-failingProject-302609671-20171115-184709_bugonly
 - [deleted]                   surli-failingProject-303053613-20171116-154536_bugonly
 - [deleted]                   surli-failingProject-303139956-20171116-184722_bugonly
 - [deleted]                   surli-failingProject-303566340-20171117-154633_bugonly
 - [deleted]                   surli-failingProject-303650350-20171117-184801_bugonly
 - [deleted]                   surli-failingProject-303987734-20171118-154633_bugonly
 - [deleted]                   surli-failingProject-304038610-20171118-184838_bugonly
 - [deleted]                   surli-failingProject-304327363-20171119-154703_bugonly
 - [deleted]                   surli-failingProject-304384272-20171119-184852_bugonly
 - [deleted]                   surli-failingProject-304776033-20171120-154802_bugonly
 - [deleted]                   surli-failingProject-304868113-20171120-185008_bugonly
 - [deleted]                   surli-failingProject-305398747-20171121-185015_bugonly
 - [deleted]                   surli-failingProject-305932299-20171122-185142_bugonly
 - [deleted]                   surli-failingProject-306433565-20171123-185539_bugonly
 - [deleted]                   surli-failingProject-306795069-20171124-154955_bugonly
 - [deleted]                   surli-failingProject-306869395-20171124-185149_bugonly
 - [deleted]                   surli-failingProject-307153110-20171125-155035_bugonly
 - [deleted]                   surli-failingProject-307499354-20171126-155153_bugonly
 - [deleted]                   surli-failingProject-307552321-20171126-185255_bugonly
 - [deleted]                   surli-failingProject-307931492-20171127-155212_bugonly
 - [deleted]                   surli-failingProject-308020306-20171127-185325_bugonly
 - [deleted]                   surli-failingProject-308559207-20171128-185401_bugonly
 - [deleted]                   surli-failingProject-309008867-20171129-155439_bugonly
 - [deleted]                   surli-failingProject-309103207-20171129-185429_bugonly
 - [deleted]                   surli-failingProject-309635838-20171130-185514_bugonly
 - [deleted]                   surli-failingProject-310072745-20171201-155404_bugonly
 - [deleted]                   surli-failingProject-310162798-20171201-185440_bugonly
 - [deleted]                   surli-failingProject-310508796-20171202-155429_bugonly
 - [deleted]                   surli-failingProject-310563177-20171202-185458_bugonly
 - [deleted]                   surli-failingProject-310873273-20171203-155518_bugonly
 - [deleted]                   surli-failingProject-310937560-20171203-185514_bugonly
 - [deleted]                   surli-failingProject-311438045-20171204-185601_bugonly
 - [deleted]                   surli-failingProject-311993249-20171205-185628_bugonly
 - [deleted]                   surli-failingProject-312460381-20171206-155853_bugonly
 - [deleted]                   surli-failingProject-312546787-20171206-185708_bugonly
 - [deleted]                   surli-failingProject-313085928-20171207-185805_bugonly
 - [deleted]                   surli-failingProject-313524854-20171208-155701_bugonly
 - [deleted]                   surli-failingProject-313608197-20171208-185821_bugonly
 - [deleted]                   surli-failingProject-314035250-20171209-185932_bugonly
 - [deleted]                   surli-failingProject-314402170-20171210-190025_bugonly
 - [deleted]                   surli-failingProject-314911998-20171211-190050_bugonly
 - [deleted]                   surli-failingProject-315399649-20171212-155900_bugonly
 - [deleted]                   surli-failingProject-315485799-20171212-190105_bugonly
 - [deleted]                   surli-failingProject-315928284-20171213-155930_bugonly
 - [deleted]                   surli-failingProject-316014822-20171213-190114_bugonly
 - [deleted]                   surli-failingProject-316550408-20171214-190234_bugonly
 - [deleted]                   surli-failingProject-316964265-20171215-160037_bugonly
 - [deleted]                   surli-failingProject-317366964-20171216-160102_bugonly
 - [deleted]                   surli-failingProject-317418147-20171216-190244_bugonly
 - [deleted]                   surli-failingProject-317702254-20171217-160215_bugonly
 - [deleted]                   surli-failingProject-317753259-20171217-190243_bugonly
 - [deleted]                   surli-failingProject-318123893-20171218-160223_bugonly
 - [deleted]                   surli-failingProject-318665316-20171219-160252_bugonly
 - [deleted]                   surli-failingProject-318759572-20171219-190421_bugonly
 - [deleted]                   surli-failingProject-319301165-20171220-190420_bugonly
 - [deleted]                   surli-failingProject-319836482-20171221-190415_bugonly
 - [deleted]                   surli-failingProject-320257548-20171222-160418_bugonly
 - [deleted]                   surli-failingProject-320329739-20171222-190449_bugonly
 - [deleted]                   surli-failingProject-320722598-20171223-190623_bugonly
 - [deleted]                   surli-failingProject-321050918-20171224-160435_bugonly
 - [deleted]                   surli-failingProject-321101627-20171224-190611_bugonly
 - [deleted]                   surli-failingProject-321400637-20171225-160516_bugonly
 - [deleted]                   surli-failingProject-321465267-20171225-190714_bugonly
 - [deleted]                   surli-failingProject-321874392-20171226-190647_bugonly
 - [deleted]                   surli-failingProject-322275099-20171227-190723_bugonly
 - [deleted]                   surli-failingProject-322623141-20171228-190716_bugonly
 - [deleted]                   surli-failingProject-322914969-20171229-160658_bugonly
 - [deleted]                   surli-failingProject-322966107-20171229-190735_bugonly
 - [deleted]                   surli-failingProject-323180443-20171230-160640_bugonly
 - [deleted]                   surli-failingProject-323225523-20171230-190841_bugonly
 - [deleted]                   surli-failingProject-323586523-20181231-161333_bugonly
 - [deleted]                   surli-failingProject-323640466-20181231-191235_bugonly
 - [deleted]                   surli-failingProject-324227936-20180102-190935_bugonly
 - [deleted]                   surli-failingProject-324616190-20180103-160848_bugonly
 - [deleted]                   surli-failingProject-324688209-20180103-191012_bugonly
 - [deleted]                   surli-failingProject-325072957-20180104-161126_bugonly
 - [deleted]                   surli-failingProject-325142491-20180104-191036_bugonly
 - [deleted]                   surli-failingProject-325549153-20180105-191111_bugonly
 - [deleted]                   surli-failingProject-325841777-20180106-191120_bugonly
 - [deleted]                   surli-failingProject-326105208-20180107-191122_bugonly

**Comment by monperrus** [comment]
perfect, thanks.
