### ISSUE TITLE
minimize response time T1: monitor all jobs

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#376]
we could poll the build even stream given at JSON at  `https://api.travis-ci.org/jobs` very often (say 5 minutes or even less -- this URL changes very fast), and have a very quick check on the repository_id. All builds for considered projects would go in the list.

This list would be LIFO for the repair bot itself such that we always  minimize the T1 component of the response time.

**Comment by monperrus** [comment]
up

**Comment by monperrus** [comment]
Thanks!

On which machine does this run? How often?

**Comment by surli** [comment]
On repairnator for now. And it runs almost live: I fill a queue of builds to watch for ending and if it fails I start them almost instantly. In average we have 10 sec delays.

**Comment by monperrus** [comment]
Does it fill the same mongo DB or another one?

Does it also pushes to librepair-experiments?

**Comment by surli** [comment]
> Does it fill the same mongo DB or another one?

If fills the same mongoDB and the same collection for inspected builds (those we try to reproduce). However, for the scanner, it fills another collection: I don't display the results for this new scanner on the website for now. 
Note that I also record the list of blacklisted repo: it might be useful for other experiments

> Does it also pushes to librepair-experiments?

Yep, the core of the pipeline does not change.

**Comment by monperrus** [comment]
OK. Does this mean that the Cron every 2 hours does not run anymore.
