### ISSUE TITLE
add Nopol diff/patch on librepair-experiments branches

### ISSUE THREAD

**Issue by monperrus** [Spirals-Team/librepair#379]
Are the nopol patches (when they exists) put somewhere in a JSON / TXT file on librepair-experiments branches?

I don't find them here: https://github.com/Spirals-Team/librepair-experiments/tree/bonigarcia-webdrivermanager-307672023-20171127-015508

**Comment by surli** [comment]
It should be, but obviously there's still a bug.

**Comment by monperrus** [comment]
OK, in would be great to have a diff: nopol.diff

**Comment by surli** [comment]
The diff will now be added directly in the list of patches.
