### ISSUE TITLE
Refactoring: allow to pass spreadsheet ID to repairnator command line

### ISSUE THREAD

**Issue by surli** [Spirals-Team/librepair#67]
We should pass different command line argument through a config.ini file

**Comment by fermadeiral** [comment]
Simon, please, edit this issue as you told me you want now to pass some arguments to RepairNator in a different way (file?) and then I can know what you want exactly.

**Comment by surli** [comment]
I'm taking this one.

**Comment by surli** [comment]
Done in #165
