### ISSUE TITLE
Improve the current naive approach to checkout the source code of the previous build.

### ISSUE THREAD

**Issue by fermadeiral** [Spirals-Team/librepair#95]

**Comment by surli** [comment]
Solution to improve it:
  - Create a new step `ComputeSourceAndTestDirs`
  - In that step, use standard name patterns and pom.xml exploration to get all source and tests dirs even if there are multi modules projects and non-standard directory names
  - put information in JobStatus
  - use information to filter file names to checkout

**Comment by fermadeiral** [comment]
We talked about that today. I think we can close this issue.

**Comment by surli** [comment]
No we don't. It will be done but later.
